<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-C1UMIF1" name="RestAssured_folderStructure_log.TestCases.deleteEmployee" tests="5" failures="0" timestamp="28 Jan 2020 14:11:23 GMT" time="2.185" errors="1">
  <testcase name="server" time="0.001" classname="RestAssured_folderStructure_log.TestCases.deleteEmployee"/>
  <testcase name="statusCode" time="0.001" classname="RestAssured_folderStructure_log.TestCases.deleteEmployee"/>
  <testcase name="contentType" time="0.000" classname="RestAssured_folderStructure_log.TestCases.deleteEmployee">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at RestAssured_folderStructure_log.TestCases.deleteEmployee.contentType(deleteEmployee.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
    </error>
  </testcase> <!-- contentType -->
  <testcase name="deleteEmp" time="2.182" classname="RestAssured_folderStructure_log.TestCases.deleteEmployee"/>
  <testcase name="statusLine" time="0.001" classname="RestAssured_folderStructure_log.TestCases.deleteEmployee"/>
</testsuite> <!-- RestAssured_folderStructure_log.TestCases.deleteEmployee -->
